export const categories = [
  { name: 'Basics', description: 'Essential everyday words and phrases' },
  { name: 'Numbers', description: 'Numbers and counting' },
  { name: 'Common Verbs', description: 'Most frequently used verbs' },
  { name: 'Family', description: 'Family members and relationships' },
  { name: 'Time', description: 'Time-related words and expressions' },
  { name: 'Food', description: 'Food and dining vocabulary' },
  { name: 'Weather', description: 'Weather and climate terms' },
  { name: 'Places', description: 'Locations and places' },
  { name: 'Transportation', description: 'Vehicles and travel methods' },
  { name: 'Colors', description: 'Colors and visual descriptions' },
  { name: 'Professions', description: 'Jobs and occupations' },
  { name: 'Emotions', description: 'Feelings and emotional states' },
  { name: 'Body Parts', description: 'Parts of the body' },
  { name: 'Nature', description: 'Natural world and environment' },
  { name: 'Clothing', description: 'Clothes and accessories' },
  { name: 'Technology', description: 'Modern technology terms' },
  { name: 'Business', description: 'Business and work vocabulary' },
  { name: 'Education', description: 'School and learning terms' },
  { name: 'Health', description: 'Health and medical vocabulary' },
  { name: 'Entertainment', description: 'Entertainment and leisure' },
  { name: 'Sports', description: 'Sports and athletic activities' },
  { name: 'Arts', description: 'Art and creative activities' },
  { name: 'Science', description: 'Scientific terms and concepts' },
  { name: 'Music', description: 'Musical terms and instruments' },
  { name: 'Animals', description: 'Animals and wildlife' },
  { name: 'Travel', description: 'Travel and tourism vocabulary' },
  { name: 'Shopping', description: 'Shopping and retail terms' },
  { name: 'Hobbies', description: 'Hobby and leisure activities' },
  { name: 'Communication', description: 'Communication terms' },
  { name: 'Culture', description: 'Cultural terms and traditions' },
  { name: 'Environment', description: 'Environmental terms' },
  { name: 'Social Media', description: 'Social media vocabulary' },
  { name: 'Finance', description: 'Financial terms' },
  { name: 'Law', description: 'Legal terminology' },
  { name: 'Medicine', description: 'Medical vocabulary' },
  { name: 'Household', description: 'Household items and activities' },
  { name: 'Office', description: 'Office-related vocabulary' },
  { name: 'Relationships', description: 'Relationship and social terms' },
  { name: 'Personality', description: 'Character and personality traits' },
  { name: 'Directions', description: 'Directions and navigation' },
  { name: 'Measurements', description: 'Units and measurements' },
  { name: 'Materials', description: 'Materials and substances' },
  { name: 'Tools', description: 'Tools and equipment' },
  { name: 'Vehicles', description: 'Types of vehicles' },
  { name: 'Buildings', description: 'Types of buildings and structures' },
  { name: 'Geography', description: 'Geographical terms' },
  { name: 'History', description: 'Historical terms' },
  { name: 'Politics', description: 'Political vocabulary' },
  { name: 'Religion', description: 'Religious terms' },
  { name: 'Philosophy', description: 'Philosophical concepts' }
];